apiVersion: v2
name: my-bank-app
description: BankApp umbrella chart

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  # Infrastructure Dependencies
  - name: keycloak
    version: "0.1.0"
    repository: "file://../charts/keycloak"
    condition: keycloak.enabled
  
  - name: postgresql-accounts
    version: "0.1.0"
    repository: "file://../charts/postgresql-accounts"
    condition: postgresql-accounts.enabled
  
  - name: postgresql-exchange
    version: "0.1.0"
    repository: "file://../charts/postgresql-exchange"
    condition: postgresql-exchange.enabled
  
  - name: postgresql-notifications
    version: "0.1.0"
    repository: "file://../charts/postgresql-notifications"
    condition: postgresql-notifications.enabled

  # Service Dependencies
  - name: gateway-api
    version: "0.1.0"
    repository: "file://../charts/gateway-api"
    condition: gateway-api.enabled
  
  - name: front-ui
    version: "0.1.0"
    repository: "file://../charts/front-ui"
    condition: front-ui.enabled
  
  - name: accounts
    version: "0.1.0"
    repository: "file://../charts/accounts"
    condition: accounts.enabled
  
  - name: cash
    version: "0.1.0"
    repository: "file://../charts/cash"
    condition: cash.enabled
  
  - name: convert
    version: "0.1.0"
    repository: "file://../charts/convert"
    condition: convert.enabled
  
  - name: exchange
    version: "0.1.0"
    repository: "file://../charts/exchange"
    condition: exchange.enabled
  
  - name: transfer
    version: "0.1.0"
    repository: "file://../charts/transfer"
    condition: transfer.enabled
  
  - name: blocker
    version: "0.1.0"
    repository: "file://../charts/blocker"
    condition: blocker.enabled
  
  - name: notifications
    version: "0.1.0"
    repository: "file://../charts/notifications"
    condition: notifications.enabled