apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cash.fullname" . }}-secret
  labels:
    {{- include "cash.labels" . | nindent 4 }}
type: Opaque
data:
  client-secret: {{ "VmGXQDXNGOZzJH5Mx7Fi4OyHtnb3IH8A" | b64enc }}