apiVersion: v1
kind: Secret
metadata:
  name: {{ include "accounts.fullname" . }}-secret
  labels:
    {{- include "accounts.labels" . | nindent 4 }}
type: Opaque
data:
  client-secret: {{ "VmGXQDXNGOZzJH5Mx7Fi4OyHtnb3IH8A" | b64enc }}
  db-password: {{ "postgres" | b64enc }}