services:
  front-ui:
    host: ${host}
    port: 8079
    url: http://gateway-api:${services.front-ui.port}
  gateway-api:
    host: ${host}
    port: 8080
    name: gateway-api
    url: http://gateway-api:${services.gateway-api.port}
  convert:
    host: ${host}
    port: 8081
    url: http://gateway-api:${services.convert.port}
  transfer:
    host: ${host}
    port: 8082
    url: http://gateway-api:${services.transfer.port}
  blocker:
    host: ${host}
    port: 8083
    url: http://gateway-api:${services.blocker.port}
  accounts:
    host: ${host}
    port: 8084
    url: http://gateway-api:${services.accounts.port}
  exchange:
    host: ${host}
    port: 8085
    url: http://gateway-api:${services.exchange.port}
  cash:
    host: ${host}
    port: 8086
    url: http://gateway-api:${services.cash.port}
  notifications:
    host: ${host}
    port: 8087
    url: http://gateway-api:${services.notifications.port}
  externalized-config:
    host: ${host}
    port: 8888
    url: http://gateway-api:${services.externalized-config.port}

headers:
  user-header: X-User-Login

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    web: info
    org.springframework.security: info