apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "notifications.fullname" . }}-config
  labels:
    {{- include "notifications.labels" . | nindent 4 }}
data:
  # OAuth2 Configuration
  oauth2-resource-server-jwk-set-uri: "http://bankapp-keycloak:8080/realms/bankapp/protocol/openid-connect/certs"
  
  # Database Configuration
  r2dbc-url: "r2dbc:postgresql://bankapp-postgresql-notifications:5432/notifications-db"
  r2dbc-username: "postgres"